server:
  port: 3344



spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/wujing143/springcloud-config.git    # GitHub上面的git仓库地址
          ###搜索目录
          search-paths:
            - springcloud-config
      ###读取分支
      label: main

#   /分支/配置文件【  配置文件一般由   服务name-环境(dev/test/prod)  】
#  / {label} / {application}-{profile}.yml（最推荐使用这种方式）
#    http://localhost:3344/main/config-dev.yml/
#    http://localhost:3344/main/config-test.yml/
#    http://localhost:3344/main/config-prod.yml/

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

