server:
  port: 8001


spring:
  application:
    name: cloud-payment-service   # 这个名称就是 Eureka 服务注册中心的“CLOUD-PAYMENT-SERVICE”一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据库源操作类型
    driver-class-name: com.mysql.jdbc.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud_payment?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# Eureka客户端 配置
eureka:
  client:
    register-with-eureka: true   #将自己 注册进 EurekaServer 默认是true
    # 从EurekaServer 抓取已有的注册信息，默认是true 。单节点无所谓，集群必须设置true，才可以配合Ribbon使用负载均衡
    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka   #单机版
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001  #主机名的修改
    prefer-ip-address: true #访问路径可以显示IP地址

#    lease-renewal-interval-in-seconds:  1      #Eureka客户端向服务端发送心跳的时间间隔，单位s（默认30s）
#    lease-expiration-duration-in-seconds:  2   #Eureka服务端在收到最后一次心跳后等待时间的上限，单位s（默认90s），超时将被剔除服务


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities   # 所有Entity别名类所在包 [mapper.xml中可以直接 parameterType="Payment"]



