server:
  port: 9527

spring:
  application:
    name: cloud-gateway     # 这就是 Eureka 服务注册中心的名字 --> CLOUD-GATEWAY
  cloud:
    gateway:
      routes:  # 配置多个路由  【也可用代码 编码路由 bean】
        - id: payment_routh     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri:  lb://cloud-payment-service  #【通过微服务名实现动态路由】8001  8002
          predicates:
            - Path=/payment/getPayment/**   #断言,路径相匹配的进行路由  http://localhost:9527/payment/getPayment/{id}

        - id: payment_routh2
#          uri: http://localhost:8001
          uri:  lb://cloud-payment-service
          predicates:                #断言：Predicate的使用【就是对转发，做一些条件的判断】
            - After=2020-10-30T16:50:46.249+08:00[Asia/Shanghai]   #在指定时间之后，才可转发成功
            - Path=/payment/lb


eureka:
  instance:
    hostname: cloud-gateway-service  #eureka上的Status的地址的域名
    instance-id: gateway9527   #eureka 上的Status的名称
  client:
    service-url:
      register-with-eureka: true   #表识向注册中心注册自己
      fetch-registry: true         #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
      defaultZone: http://eureka7001.com:7001/eureka      #单机模式，注册到这个 eureka7001.com:7001

