server:
  port: 80

eureka:
  client:
    register-with-eureka: false   #表识不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


 #开启 Feign 里面的 Hystrix熔断
feign:
  hystrix:
    enabled:  true    #如果处理自身的容错就开启。开启方式与生产端不一样。


##hystrix的超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true        #开启 hystrix 时间检测功能
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000   #hystrix的超时时间
##ribbon的超时时间
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000